// Generated by CoffeeScript 1.6.1

(function() {
  "use strict";
  var onErr, prompt, rename;
  prompt = require("prompt");
  rename = require("./scripts.coffee").rename;
  prompt.start;
  prompt.get(["path", "re", "replacement"], function(err, result) {
    if (err) {
      onErr(err);
    }
    return rename(result.path, new RegExp(result.re), result.replacement);
  });
  return onErr = function(err) {
    console.log(err);
    return 1;
  };
}).call(this);
