// Generated by CoffeeScript 1.6.1

(function() {
  "use strict";
  var onErr, prompt, scripts;
  prompt = require("prompt");
  scripts = require("./scripts.coffee");
  prompt.start;
  prompt.get(["folder", "re"], function(err, result) {
    if (err) {
      onErr(err);
    }
    scripts.summarize(result.folder, new RegExp(result.re, "g"));
    scripts.compare(result.folder);
    return console.log("Deposited Diffs");
  });
  return onErr = function(error) {
    console.log(error);
    return 1;
  };
}).call(this);
