// Generated by CoffeeScript 1.6.1
var RSLCounterTimer,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

RSLCounterTimer = (function() {
  var Counter, CounterTimer, Timer;

  function RSLCounterTimer() {}

  RSLCounterTimer.CounterTimer = CounterTimer = (function() {

    function CounterTimer(number, preset) {
      this.number = number;
      this.preset = preset;
      this.acc = 0;
      this.en = true;
      this.dn = this.done();
    }

    CounterTimer.prototype.tickUp = function() {
      this.acc++;
      return this.dn = this.done();
    };

    CounterTimer.prototype.tickDown = function() {
      this.acc--;
      return this.dn = this.done();
    };

    CounterTimer.prototype.done = function() {
      return this.acc >= this.preset;
    };

    return CounterTimer;

  })();

  RSLCounterTimer.Counter = Counter = (function(_super) {

    __extends(Counter, _super);

    function Counter() {
      return Counter.__super__.constructor.apply(this, arguments);
    }

    Counter.prototype.CU = function() {
      this.tickUp();
      return this.cu = true;
    };

    Counter.prototype.CD = function() {
      this.tickDown();
      return this.cu = true;
    };

    Counter.prototype.OV = function() {};

    Counter.prototype.UV = function() {};

    return Counter;

  })(RSLCounterTimer.CounterTimer);

  RSLCounterTimer.Timer = Timer = (function(_super) {

    __extends(Timer, _super);

    function Timer() {
      return Timer.__super__.constructor.apply(this, arguments);
    }

    Timer.prototype.tick = function() {
      if (!this.done()) {
        this.tickUp();
        return this.tt = true;
      } else {
        return this.tt = false;
      }
    };

    return Timer;

  })(RSLCounterTimer.CounterTimer);

  RSLCounterTimer.counterTimerInstruction = function(file, action) {
    return function(matchValues, dataTable) {
      var number, preset, unit;
      number = matchValues[0], preset = matchValues[1];
      dataTable[file] = dataTable[file] || {};
      dataTable[file][number] = dataTable[file][number] || new this.CounterTimer(number, preset);
      unit = dataTable[file][number];
      return dataTable = action(unit);
    };
  };

  RSLCounterTimer.timerInstruction = function(timerAction) {
    return this.counterTimerInstruction("T4", timerAction);
  };

  RSLCounterTimer.TON = RSLCounterTimer.timerInstruction(function(timer) {});

  RSLCounterTimer.TOF = RSLCounterTimer.timerInstruction(function(timer) {});

  RSLCounterTimer.RTO = RSLCounterTimer.timerInstruction(function(timer) {});

  RSLCounterTimer.RES = function(matchValues, dataTable) {
    var file, matchText, rank;
    matchText = matchValues[0], file = matchValues[1], rank = matchValues[2];
    return dataTable[file][rank].acc = 0;
  };

  RSLCounterTimer.counterInstruction = function(counterAction) {
    return this.counterTimerInstruction("C5", counterAction);
  };

  RSLCounterTimer.CTU = RSLCounterTimer.counterInstruction(function(counter) {});

  RSLCounterTimer.CTD = RSLCounterTimer.counterInstruction(function(counter) {});

  return RSLCounterTimer;

})();
