// Generated by CoffeeScript 1.6.1
var RSLInput;

RSLInput = (function() {

  function RSLInput() {}

  RSLInput.bitwiseInput = function(bitwiseFunction) {
    return function(matchValues, dataTable) {
      var bit, file, matchText, rank;
      matchText = matchValues[0], file = matchValues[1], rank = matchValues[2], bit = matchValues[3];
      if (bitwiseFunction(dataTable[file][rank][bit])) {
        return dataTable;
      } else {
        return false;
      }
    };
  };

  RSLInput.XIC = RSLInput.bitwiseInput(function(bit) {
    return bit === true || bit === 1;
  });

  RSLInput.XIO = RSLInput.bitwiseInput(function(bit) {
    return bit === false || bit === 0;
  });

  return RSLInput;

})();
