// Generated by CoffeeScript 1.6.1
var RSLOutput;

RSLOutput = (function() {

  function RSLOutput() {}

  RSLOutput.bitwiseOutput = function(set, latchAction) {
    if (latchAction == null) {
      latchAction = function() {};
    }
    return function(matchValues, dataTable) {
      var bit, file, matchText, rank;
      matchText = matchValues[0], file = matchValues[1], rank = matchValues[2], bit = matchValues[3];
      dataTable[file] = dataTable[file] || {};
      dataTable[file][rank] = dataTable[file][rank] || {};
      dataTable[file][rank][bit] = set;
      return dataTable = latchAction(dataTable);
    };
  };

  RSLOutput.OTE = RSLOutput.bitwiseOutput(true);

  RSLOutput.OTL = RSLOutput.bitwiseOutput(true, function(dataTable) {
    dataTable["latch"] = dataTable["latch"] || [];
    if (dataTable["latch"].indexOf({
      file: file,
      rank: rank,
      bit: bit
    } === -1)) {
      dataTable["latch"].push({
        file: file,
        rank: rank,
        bit: bit
      });
    }
    return dataTable;
  });

  RSLOutput.OTU = RSLOutput.bitwiseOutput(false, function(dataTable) {
    var removeIndex;
    if (dataTable["latch"] != null) {
      removeIndex = dataTable["latch"].indexOf({
        file: file,
        rank: rank,
        bit: bit
      });
    }
    if (removeIndex !== -1) {
      dataTable.splice(removeIndex, 1);
    }
    return dataTable;
  });

  return RSLOutput;

})();
