// Generated by CoffeeScript 1.6.1
var RSLOneShot;

RSLOneShot = (function() {

  function RSLOneShot() {}

  RSLOneShot.OSR = function(matchValues, dataTable) {
    var bit, file, findObject, foundOneShots, matchText, rank;
    matchText = matchValues[0], file = matchValues[1], rank = matchValues[2], bit = matchValues[3];
    if (dataTable[file][rank][bit]) {
      return false;
    } else {
      dataTable[file][rank][bit] = true;
      dataTable["oneShots"] = dataTable["oneShots"] || [];
      findObject = {
        file: file,
        rank: rank,
        bit: bit
      };
      foundOneShots = dataTable["oneShots"].find(findObject);
      if (foundOneShots.length === 0) {
        dataTable["oneShots"].push({
          file: file,
          rank: rank,
          bit: bit,
          active: true
        });
      } else {
        dataTable["oneShots"].update(findObject, {
          file: file,
          rank: rank,
          bit: bit,
          active: true
        });
      }
      return dataTable;
    }
  };

  return RSLOneShot;

})();
