// Generated by CoffeeScript 1.6.1
var RSLStartEnd;

RSLStartEnd = (function() {

  function RSLStartEnd() {}

  RSLStartEnd.SOR = function(matchValues, dataTable) {
    var matchText, rungNumber;
    matchText = matchValues[0], rungNumber = matchValues[1];
    dataTable.rungs = dataTable.rungs || [];
    dataTable.rungs.push(rungNumber);
    dataTable.activeRung = rungNumber;
    dataTable.rungOpen = true;
    dataTable.programOpen = true;
    return dataTable;
  };

  RSLStartEnd.ending = function(lastAction, errorMessage) {
    if (errorMessage == null) {
      errorMessage = "EOR does not match SOR";
    }
    return function(matchValues, dataTable) {
      var matchText, rungNumber;
      matchText = matchValues[0], rungNumber = matchValues[1];
      if (rungNumber === dataTable.activeRung) {
        dataTable.rungOpen = false;
        if (typeof lastAction === "Function") {
          lastAction;
        }
        return dataTable;
      } else {
        throw "EOR does not match SOR";
      }
    };
  };

  RSLStartEnd.EOR = RSLStartEnd.ending;

  RSLStartEnd.END = RSLStartEnd.ending(function() {
    return dataTable.programOpen = false;
  }, "END does not match SOR");

  return RSLStartEnd;

})();
