// Generated by CoffeeScript 1.6.1

(function() {
  "use strict";  process.env.test = true;
  return describe("RSLParser", function() {
    var RSLParser;
    RSLParser = require("../../models/RSLParserComplete.coffee");
    it("should exist", function() {
      return expect(RSLParser).toBeDefined;
    });
    return describe("execute method", function() {
      it("returns the dataTable on unrecognized instruction", function() {
        return expect(RSLParser.execute("what", {
          data: "table"
        })).toEqual({
          data: "table"
        });
      });
      return describe("executing start and end instructions", function() {
        it("Starts a rung with SOR", function() {
          return expect(RSLParser.execute("SOR,0", {
            data: "table"
          })).toEqual({
            data: 'table',
            rungs: ['0'],
            activeRung: '0',
            rungOpen: true,
            programOpen: true
          });
        });
        return it("Ends a rung with EOR", function() {
          return expect(RSLParser.execute("EOR,0", {
            rungOpen: true,
            programOpen: true,
            activeRung: "0",
            rungs: ['0']
          }).rungOpen).toBe(false);
        });
      });
    });
  });
}).call(this);
